### ISSUE TITLE
File translation results different from interactive outputs

### ISSUE THREAD

**Issue by Evandernyoni** [joeynmt/joeynmt#143]
**Describe the bug**
File translation results are different from interactive translation outputs.

**To Reproduce**

I used the following command for generating file translations:

```
python3 -m joeynmt translate configs/small.yaml < my_input.txt > out.
```
To generate translations the interactive way: 

```
python3 -m joeynmt translate configs/small.yaml
```

The interactive translation outputs are better than the file translation outputs.

**Comment by juliakreutzer** [comment]
Hi @Evandernyoni
is `my_input.txt` referred to in the config for the second case?

**Comment by Evandernyoni** [comment]
Hi Juliea

Yes the file is referred to in the config file.

Regards

**Comment by Evandernyoni** [comment]
Hi @juliakreutzer 

In the interactive translations, I applied the same per-processing steps to the new input as in the case of the of model training (i.e. splitting into sub-words).  The parameters in the config file are as follows:

```
testing:
    beam_size: 5
    alpha: 1.0
    sacrebleu:                      # sacrebleu options
        remove_whitespace: True     # `remove_whitespace` option in sacrebleu.corpus_chrf() function (defalut: True)
        tokenize: "intl"            # `tokenize` option in sacrebleu.corpus_bleu() function (options include: "none" (use for already tokenized test data), "13a" (default minimal tokenizer), "intl" which mostly does punctuation and unicode, etc) 

training:
    #load_model: "models/{name}_transformer/1.ckpt" # if uncommented, load a pre-trained model from this checkpoint
    random_seed: 42
    optimizer: "adam"
    normalization: "tokens"
    adam_betas: [0.9, 0.999] 
    scheduling: "plateau"           
    patience: 5                     
    learning_rate_factor: 0.5       
    learning_rate_warmup: 1000      
    decrease_factor: 0.7
    loss: "crossentropy"
    learning_rate: 0.0003
    learning_rate_min: 0.00000001
    weight_decay: 0.0
    label_smoothing: 0.1
    batch_size: 4096
    batch_type: "token"
    eval_batch_size: 3600
    eval_batch_type: "token"
    batch_multiplier: 1
    early_stopping_metric: "ppl"
    epochs: 30
    validation_freq: 2000          
    logging_freq: 200
    eval_metric: "bleu"
    model_dir: "models/{name}_transformer"
    overwrite: True               
    shuffle: True
    use_cuda: True
    max_output_length: 100
    print_valid_sents: [0, 1, 2, 3]
    keep_last_ckpts: 3

model:
    initializer: "xavier"
    bias_initializer: "zeros"
    init_gain: 1.0
    embed_initializer: "xavier"
    embed_init_gain: 1.0
    tied_embeddings: True       
    tied_softmax: True
    encoder:
        type: "transformer"
        num_layers: 6
        num_heads: 8             
        embeddings:
            embedding_dim: 512   
            scale: True
            dropout: 0.2
        # typically ff_size = 4 x hidden_size
        hidden_size: 512         
        ff_size: 2048            
        dropout: 0.1
    decoder:
        type: "transformer"
        num_layers: 6
        num_heads: 8              
        embeddings:
            embedding_dim: 512    
            scale: True
            dropout: 0.2
        # typically ff_size = 4 x hidden_size
        hidden_size: 512        
        ff_size: 2048            
        dropout: 0.1

```
