### ISSUE TITLE
Running build_vocab.py for wmt17_bpe with or without --joint?  

### ISSUE THREAD

**Issue by AlexWang1900** [joeynmt/joeynmt#209]
**Describe the bug**

**To Reproduce**
1. task description: running the default wmt17_ende_bpe
2. configuration file : wmt17_ende_bpe.py in this github
3. code call : python build_vocab.py configs/wmt17_ende_bpe.py

**Logged output**
### Training bpe...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32000/32000 [01:31<00:00, 349.71it/s]
### Training bpe...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32000/32000 [03:04<00:00, 173.51it/s]
### Done.

**Expected behavior**
de and en should bpe should both be there, no overwritten. 

**System (please complete the following information):**
 - OS: ubuntu 22.04
 - CPU / GPU: 9900k+4090
 - Python Version: 3.9

**Additional context**
if I use: build_vocab.py configs/wmt17_ende_bpe.py --joint, an assert triggered in line 312 in build_vocab.py
    if args.joint:
        for s, t in zip(src_tuple[1:], trg_tuple[1:]):
            assert s == t

**Comment by AlexWang1900** [comment]
I think I found the bug:
in wmt17_ende_bpe.py:

```
src:
        lang: "en"
        max_length: 512
        lowercase: False
        normalize: True
        level: "bpe"
        voc_min_freq: 1
        **voc_limit: 32000**
        voc_file: "subwords/wmt17_bpe.vocab"
        tokenizer_type: "subword-nmt"
        tokenizer_cfg:
            num_merges: 32000
            codes: "subwords/wmt17_bpe.codes"
            dropout: 0.1
            pretokenizer: "moses"
```

left a line : **voc_limit: 32000**
